
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "firstName": "Kirigaya",
  "middleName": "Kazu",
  "lastName": "Kazuto",
  "birthdate": "November 2, 1994",
  "status": "Inactive"
}

###
GET http://localhost:3000/api/users HTTP/1.1

###
GET http://localhost:3000/api/users/5cd514495022ea7f72e4e40f HTTP/1.1

###
PATCH http://localhost:3000/api/users/5cd514495022ea7f72e4e40f HTTP/1.1
Content-Type: application/json

{
  "firstName": "Mikhael",
  "middleName": "Santos",
  "lastName": "Oriel",
  "birthdate": "November 2, 1994",
  "status": "Active"
}

###
DELETE http://localhost:3000/api/users/5cd52abff2cd9c6f1b884494 HTTP/1.1

